[pytest]
# Run in headed mode by default, 3 workers for parallel execution and manage traces
addopts = --headed --browser chromium -n 3 --tracing retain-on-failure
testpaths = tests
python_files = test_*.py
